name: "Dev Terraform Workflow"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted   # ya phir wahi label jo runner me hai (ex: GitHub_DevOps)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Plan
        run: terraform -chdir=env/dev plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=env/dev apply -auto-approve tfplan
